networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
  mariadb:
    name: mariadb

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    restart: unless-stopped
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
#    depends_on:
#      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
  
#  mariadb:
#    container_name: mariadb
#    build: requirements/mariadb/
#    volumes:
#      - mariadb:/var/lib/mysql
#    env_file:
#      - .env
#    networks:
#      - inception
#    restart: unless-stopped
