volumes:
  wordpress:
    name: wordpress
  mariadb:
    name: mariadb

networks:
  inception:
    name: inception

services:
  
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    volumes:
      - wordpress:/var/www/html/
    networks: 
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
