server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name ylabussi.42.fr;
	ssl_certificate /inception.crt;
	ssl_certificate_key /inception.key;
	ssl_protocols TLSv1.3;

	index index.html index.php;
	root /var/www;
	location / {
	
	}
}
